# Generated by Django 4.2.19 on 2025-06-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_funcionario_remove_compra_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='usuario_temp', max_length=150, unique=True),
        ),
    ]
