# Generated by Django 4.2.19 on 2025-06-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_adm',
            field=models.BooleanField(default=False),
        ),
    ]
