# Generated by Django 4.2.19 on 2025-06-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customuser_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cpf',
        ),
    ]
