# Generated by Django 4.2.19 on 2025-06-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_customuser_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao_pro',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='img_prod',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='qtd_prod',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tipo_prod',
        ),
        migrations.AddField(
            model_name='produto',
            name='classe',
            field=models.CharField(default='Alimento', max_length=100, verbose_name='Classificação'),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, max_length=350, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem do Produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_produto',
            field=models.CharField(default='Outro', max_length=100, verbose_name='Tipo de Embalagem'),
        ),
        migrations.AddField(
            model_name='produto',
            name='validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade'),
        ),
    ]
