# Generated by Django 4.2.19 on 2025-06-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_produto_descricao_pro_remove_produto_img_prod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='loja',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='loja'),
        ),
    ]
