# Generated by Django 4.2.19 on 2025-06-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_customuser_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='exibir_no_carrinho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='is_disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponível para Carrinho'),
        ),
    ]
