# Generated by Django 4.2.19 on 2025-06-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_data_compra_compra_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenscompra',
            name='carrinho',
        ),
        migrations.RemoveField(
            model_name='itenscompra',
            name='compra',
        ),
        migrations.DeleteModel(
            name='Carrinho',
        ),
        migrations.DeleteModel(
            name='ItensCompra',
        ),
    ]
