# Generated by Django 4.2.19 on 2025-03-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='ano_publicado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
